### ISSUE TITLE
我的golang的包管理方法

### ISSUE THREAD

**Issue by Chyroc** [Chyroc/chyroc.github.io#26]
# 我的golang的包管理方法

## 现有的工具

- dep
- glide
- govendor

## 问题

- 墙外包
- 项目路径有大小写，但是引用的包里面用的不一致，导致问题
- git ssh拉包
- 登录翻墙vpn+和登录公司内网vpn冲突
- ss不支持终端

## 现在的方法

- 使用`https://github.com/godcong/glide`版本的glide，对`mirror`进行了修复和增强

- 添加`mirrors.yaml`到`~/.glide/mirrors.yaml`
```
repos:
- original: https://golang.org/x/crypto
  repo: https://github.com/golang/crypto
  vcs: git
- original: https://golang.org/x/crypto/bcrypt
  repo: https://github.com/golang/crypto
  vcs: git
  base: golang.org/x/crypto
- original: https://golang.org/x/crypto/acme/autocert
  repo: https://github.com/golang/crypto
  vcs: git
  base: golang.org/x/crypto
- original: https://golang.org/x/image
  repo: https://github.com/golang/image
  vcs: git
- original: https://golang.org/x/mobile
  repo: https://github.com/golang/mobile
  vcs: git
- original: https://golang.org/x/net
  repo: https://github.com/golang/net
  vcs: git
- original: https://golang.org/x/net/context
  repo: https://github.com/golang/net
  vcs: git
  base: golang.org/x/net
- original: https://golang.org/x/net/html
  repo: https://github.com/golang/net
  vcs: git
  base: golang.org/x/net
- original: https://golang.org/x/net/http2
  repo: https://github.com/golang/net
  vcs: git
  base: golang.org/x/net
- original: https://golang.org/x/sys
  repo: https://github.com/golang/sys
  vcs: git
- original: https://golang.org/x/sys/unix
  repo: https://github.com/golang/sys
  vcs: git
  base: golang.org/x/sys
- original: https://golang.org/x/text
  repo: https://github.com/golang/text
  vcs: git
- original: https://golang.org/x/text/unicode/norm
  repo: https://github.com/golang/text
  vcs: git
  base: golang.org/x/text
- original: https://golang.org/x/text/secure/bidirule
  repo: https://github.com/golang/text
  vcs: git
  base: golang.org/x/text
- original: https://golang.org/x/tools
  repo: https://github.com/golang/tools
  vcs: git
- original: https://golang.org/x/oauth2
  repo: https://github.com/golang/oauth2
  vcs: git
- original: https://google.golang.org/appengine/urlfetch
  repo: https://github.com/golang/appengine
  base: google.golang.org/appengine
  vcs: git
- original: https://google.golang.org/appengine
  repo: https://github.com/golang/appengine
  vcs: git
- original: https://google.golang.org/grpc
  repo: https://github.com/grpc/grpc-go
  vcs: git
- original: https://google.golang.org/genproto
  repo: https://github.com/google/go-genproto
  vcs: git
- original: https://google.golang.org/genproto/googleapis/rpc/status
  repo: https://github.com/google/go-genproto
  vcs: git
  base: google.golang.org/genproto
```

## 更新mirror

上面的mirror总是一部分，如果你也有一个墙外包，可以按照下面的方法添加：

- 去 `https://gowalker.org` 搜索该包
- 如 `https://google.golang.org/appengine/urlfetch`对应`https://gowalker.org/google.golang.org/appengine/urlfetch`
- 向上级点开，知道页面出现`显示 README 内容`
- 点开并搜索 `<some readme> site:github.com`: `https://www.google.com/search?q=Go+App+Engine+packages+site%3Agithub.com&oq=Go+App+Engine+packages+site%3Agithub.com&aqs=chrome..69i57j69i64l3.5944j0j1&sourceid=chrome&ie=UTF-8`
- 出现的结果第一个就是`https://github.com/golang/appengine`
